# tf_bridge configuration.
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/default/model/double_pendulum_rail/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/double_pendulum_rail/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  lazy: true
  direction: GZ_TO_ROS

- ros_topic_name: "/trolley_speed_cmd"
  gz_topic_name: "/model/double_pendulum_rail/joint/rail_trolley_joint/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "gz.msgs.Wrench"
  lazy: true
  direction: ROS_TO_GZ