- ros_topic_name: "/double_pendulum_rail/joint_states"
  gz_topic_name: "/model/double_pendulum_rail/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/double_pendulum_rail/link_pose"
  gz_topic_name: "/model/double_pendulum_rail/pose"
  ros_type_name: "geometry_msgs/msg/PoseStamped"
  gz_type_name: "ignition.msgs.Pose"
  direction: GZ_TO_ROS